title: Project

pages: false

options:
  delete: false

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea

fields:
  title:
    label: Project name
    type: text
  brief:
    label: Project brief
    type: textArea
