title: Project

pages: false

options:
  delete: true

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea

fields:
  title:
    label: Project Name
    type: textArea
  brief:
    label: Project Brief
    type: textArea
  tags:
    label: Tags
    type: tags
    lower: true
  projectlink:
    label: Project URL
    type: url
    required: false
